name: Run pytest 

on: [push]

jobs:
  example-1:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.7"]
    steps:
      - uses: conda-incubator/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Conda list
        shell: pwsh
        run: conda list
      - name: where am I 
        shell: pwsh
        run:  ls -a 
      - name: install dependencies
        shell: pwsh
        run: |
          conda install -c omnia openmm  
          conda install pip 
          pip install -r ../requirements.txt 
          pip install -e .. 
      - name: Test with pytest
        run: |          
          pytest
