name: Run pytest 

on: [push]

jobs:
  example-2-linux:
    name: Ex2 Linux
    runs-on: "ubuntu-latest"
    steps:
      - uses: conda-incubator/setup-miniconda@v1
        with:
          python-version: 3.7
          activate-environment: foo
      - name: Bash
        shell: bash -l {0}
        run: |
          conda info
          conda list

      - name: where am I 
        shell: bash -l {0}
        run:  ls -a 
      - name: install dependencies
        shell: bash -l {0}
        run: |
          conda install -c omnia openmm  
          conda install pip 
          pip install -r ../requirements.txt 
          pip install -e .. 
      - name: Test with pytest
        shell: bash -l {0}
        run: |          
          pytest
