name: Run pytest 

on: [push]

jobs:
  build:
    name: build
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v1
        with:
          python-version: 3.7
          auto-activate-base: true
      - shell: bash -l {0}
        run: |
          conda activate test 
          conda info
          conda list
      - run: which python
        
      - name: Install dependencies
        run: |
          conda install -c omnia openmm  
          conda install pip 
          pip install -r requirements.txt 
          pip install -e . 
      - name: Test with pytest
        run: |          
          pytest
