name: Run pytest 

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - uses: conda-incubator/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: 3.7
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Conda list
        shell: pwsh
        run: conda list
              
      - run: conda --version
      - run: which python
      - name: Install dependencies
        run: |
          conda install -c omnia openmm  
          conda install pip 
          pip install -r requirements.txt 
          pip install -e . 
      - name: Test with pytest
        run: |          
          pytest
